/* MONOCHROME® — command bar. Press / or Ctrl/Cmd+K on any page, type, and jump to a page, a shop category or any piece.
   Loaded on demand by core.js; the list comes from js/search-index.js (generated by scripts/build.mjs). */
(() => {
  'use strict';
  const MC = window.MC;
  if (!MC || MC.palette) return;
  const $ = (s, r = document) => r.querySelector(s);
  const box = $('#cmd'), input = $('#cmdQ'), list = $('#cmdList');
  if (!box || !input || !list) return;
  const TAG = { page: 'PAGE', cat: 'KIND', piece: 'PIECE', store: 'STORE' };
  let index = null, results = [], sel = 0, lastFocus = null, loading = false;

  function withIndex(cb) {
    if (window.MC_INDEX) { index = window.MC_INDEX; return cb(); }
    if (loading) return;
    loading = true;
    const s = document.createElement('script');
    s.src = MC.asset('js/search-index.js');
    s.onload = () => { index = window.MC_INDEX || []; cb(); };
    s.onerror = () => { index = []; cb(); };
    document.head.appendChild(s);
  }
  const norm = s => String(s).toLowerCase().normalize('NFKD').replace(/[̀-ͯ]/g, '').replace(/[^a-z0-9$ ]+/g, ' ').replace(/\s+/g, ' ').trim();

  function score(e, toks) {
    const n = e._n || (e._n = norm(e.n)), k = e._k || (e._k = norm(`${e.k} ${e.s}`));
    let total = 0;
    for (const t of toks) {
      let s = 0;
      if (n.startsWith(t)) s = 40; else if (n.includes(' ' + t)) s = 26; else if (n.includes(t)) s = 14; else if (k.includes(t)) s = 6;
      if (!s) return 0;
      total += s;
    }
    return total;
  }
  const hrefOf = e => (e.t === 'store' ? MC.store + e.u : MC.url(e.u));

  function run(q) {
    const toks = norm(q).split(' ').filter(Boolean);
    if (!toks.length) {
      const pages = index.filter(e => e.t === 'page' || e.t === 'cat' || e.t === 'store');
      results = [...pages, ...index.filter(e => e.t === 'piece').slice(0, 6)];
    } else {
      results = index.map((e, i) => [e, score(e, toks), i]).filter(r => r[1] > 0).sort((a, b) => b[1] - a[1] || a[2] - b[2]).slice(0, 14).map(r => r[0]);
    }
    sel = 0;
    draw();
  }
  function draw() {
    if (!results.length) { list.innerHTML = '<li class="cmd-empty" role="presentation">Nothing matches. Try “ring”, “hoodie” or “shipping”.</li>'; input.removeAttribute('aria-activedescendant'); return; }
    list.innerHTML = results.map((e, i) => `<li id="cmd-o-${i}" role="option" aria-selected="${i === sel}" data-i="${i}">
      ${e.i ? `<span class="c-img"><img alt="" loading="lazy" src="${MC.esc(e.i)}" width="36" height="44"></span>` : `<span class="c-t">${TAG[e.t] || ''}</span>`}
      <span class="c-n"><b>${MC.esc(e.n)}</b><small>${MC.esc(e.s)}</small></span>
      <svg class="ic c-go" aria-hidden="true"><use href="#i-${e.t === 'store' ? 'ne' : 'right'}"/></svg></li>`).join('');
    input.setAttribute('aria-activedescendant', `cmd-o-${sel}`);
  }
  function move(d) {
    if (!results.length) return;
    sel = (sel + d + results.length) % results.length;
    [...list.children].forEach((li, i) => li.setAttribute('aria-selected', i === sel));
    const li = list.children[sel]; if (li) li.scrollIntoView({ block: 'nearest' });
    input.setAttribute('aria-activedescendant', `cmd-o-${sel}`);
  }
  function go(i) {
    const e = results[i]; if (!e) return;
    const href = hrefOf(e);
    close(true);
    if (e.t === 'store') window.open(href, '_blank', 'noopener'); else location.href = href;
  }

  const bg = () => [...document.querySelectorAll('main,header.nav,footer,.hud,.cursor,.progress')];
  function open() {
    if (!box.hidden) return;
    withIndex(() => {
      lastFocus = document.activeElement;
      box.hidden = false;
      document.documentElement.style.overflow = 'hidden';
      bg().forEach(el => el.setAttribute('inert', ''));
      input.value = '';
      run('');
      input.focus();
    });
  }
  function close(keepFocus) {
    if (box.hidden) return;
    box.hidden = true;
    document.documentElement.style.overflow = '';
    bg().forEach(el => el.removeAttribute('inert'));
    if (!keepFocus && lastFocus && lastFocus.focus) lastFocus.focus({ preventScroll: true });
  }

  input.addEventListener('input', () => run(input.value));
  box.addEventListener('keydown', e => {
    if (e.key === 'Escape') { e.preventDefault(); close(); }
    else if (e.key === 'ArrowDown') { e.preventDefault(); move(1); }
    else if (e.key === 'ArrowUp') { e.preventDefault(); move(-1); }
    else if (e.key === 'Enter') { e.preventDefault(); go(sel); }
    else if (e.key === 'Tab') {
      const f = [input, $('.cmd-x', box)];
      const i = f.indexOf(document.activeElement);
      e.preventDefault(); f[(i + (e.shiftKey ? -1 : 1) + f.length) % f.length].focus();
    }
  });
  box.addEventListener('click', e => {
    if (e.target.closest('[data-cmd-close]')) return close();
    const li = e.target.closest('li[data-i]'); if (li) go(+li.dataset.i);
  });
  list.addEventListener('pointermove', e => {
    const li = e.target.closest('li[data-i]'); if (!li || +li.dataset.i === sel) return;
    sel = +li.dataset.i;
    [...list.children].forEach((x, i) => x.setAttribute('aria-selected', i === sel));
    input.setAttribute('aria-activedescendant', `cmd-o-${sel}`);
  });
  // coming back with the back button must not leave the bar open or the page inert
  addEventListener('pageshow', () => { if (!box.hidden) close(true); });

  MC.palette = { open, close };
  withIndex(() => {});   // fetch the list now so the first open is instant
})();
